trigger:
- main

variables:
  dockerRegistryServiceConnection: 'azure-aks-connection'   # Your Azure DevOps service connection name
  imageRepository: 'flask-new-app'                          # New image name
  containerRegistry: 'khushiacr321.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'                                   # Unique image tag per build

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image to ACR
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push Image to ACR
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: DeployToAKS
  displayName: Deploy to AKS
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "Injecting Build ID into deployment.yaml..."
        sed -i 's|__IMAGE_TAG__|$(Build.BuildId)|g' manifests/deployment.yaml
      displayName: Replace image tag dynamically

    - task: Kubernetes@1
      displayName: Deploy to AKS
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'azure-aks-connection'
        azureResourceGroup: 'flask-rg'
        kubernetesCluster: 'flask-aks'
        namespace: 'default'
        command: apply
        useConfigurationFile: true
        configuration: |
          manifests/deployment.yaml
          manifests/service.yaml
