trigger:
- main

variables:
  dockerRegistryServiceConnection: 'azure-aks-connection'
  imageRepository: 'flask-new-app'
  containerRegistry: 'khushiacr321.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image to ACR
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)

- stage: DeployToAKS
  displayName: Deploy to AKS
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "Injecting image tag into deployment.yaml"
        sed -i 's|__IMAGE_TAG__|$(Build.BuildId)|g' manifests/deployment.yaml
      displayName: Replace image tag

    - task: Kubernetes@1
      displayName: Apply Kubernetes Manifests
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'azure-aks-connection'
        azureResourceGroup: 'flask-rg'
        kubernetesCluster: 'flask-aks'
        namespace: 'default'
        command: apply
        useConfigurationFile: true
        configuration: |
          manifests/deployment.yaml
          manifests/service.yaml
