trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'flask-new-app'

stages:
- stage: BuildAndPush
  displayName: Build and Push to ACR
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Image
    steps:
    - task: Checkout@1

    - task: Docker@2
      displayName: Build Docker image
      inputs:
        containerRegistry: 'khushiacr321'        # ACR service connection name in Azure DevOps
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: BuildAndPush
  jobs:
  - job: DeployToAKS
    displayName: Deploy to AKS
    steps:
    - task: Kubernetes@1
      displayName: Apply Deployment
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'azure-aks-connection'
        azureResourceGroup: 'Aks-RG'
        kubernetesCluster: 'flask-aks'
        namespace: default
        command: apply
        useConfigurationFile: true
        configuration: 'manifests/deployment.yaml'

    - task: Kubernetes@1
      displayName: Apply Service
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'azure-aks-connection'
        azureResourceGroup: 'Aks-RG'
        kubernetesCluster: 'flask-aks'
        namespace: default
        command: apply
        useConfigurationFile: true
        configuration: 'manifests/service.yaml'
